import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../styles/globals.scss';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import BackToTopButton from '@/components/BackToTopButton';

const gilroy = localFont({
  src: [
    {
      path: '../../fonts/Gilroy-Light.woff2',
      weight: '300',
    },
    {
      path: '../../fonts/Gilroy-Regular.woff2',
      weight: '400',
    },
    {
      path: '../../fonts/Gilroy-Medium.woff2',
      weight: '500',
    },
    {
      path: '../../fonts/Gilroy-Semibold.woff2',
      weight: '600',
    },
    {
      path: '../../fonts/Gilroy-Bold.woff2',
      weight: '700',
    },
  ],
  variable: '--font-gilroy',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    //suppressHydrationWarning
    <html lang='en'>
      <body className={[`${gilroy.variable}`, 'demo-1', 'loading'].join(' ')}>
        <Header />
        <BackToTopButton />
        {children}
        <Footer />
      </body>
    </html>
  );
}
